title = 'Botanophobia'
baseURL = 'https://wonderful-forest-0f1b77103.3.azurestaticapps.net'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = false

markup.highlight.noClasses = false
theme = 'docura'
